name    'alkivi-ssh'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-ssh'
author 'alkivi'
license 'LGPLv3'
summary 'Controls SSH servers'
description 'Setup SSH servers'
project_page 'https://github.com/alkivi-sas/puppet-ssh'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
dependency 'puppetlabs/apache', '>0.x'
dependency 'alkivi/alkivi_base', '>0.x'
