name    'alkivi-owncloud'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-owncloud'
author 'alkivi'
license 'LGPLv3'
summary 'Controls owncloud deployement'
project_page 'https://github.com/alkivi-sas/puppet-owncloud'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/apt', '>1.x'
dependency 'alkivi/mysql', '>0.x'
