name    'alkivi-console_data'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-console_data'
author 'alkivi'
license 'LGPLv3'
summary 'Controls console-data'
description 'Setup console-data keymap and stuff'
project_page 'https://github.com/alkivi-sas/puppet-console_data'
#dependency 'puppetlabs/stdlib', '>3.x'
